//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Invoices.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj artykuły.
        /// </summary>
        public static string btnAddItems {
            get {
                return ResourceManager.GetString("btnAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorcy.
        /// </summary>
        public static string btnConsumers {
            get {
                return ResourceManager.GetString("btnConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj.
        /// </summary>
        public static string btnCreator {
            get {
                return ResourceManager.GetString("btnCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klienci.
        /// </summary>
        public static string btnCustomers {
            get {
                return ResourceManager.GetString("btnCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane.
        /// </summary>
        public static string btnData {
            get {
                return ResourceManager.GetString("btnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj rachunek.
        /// </summary>
        public static string btnGenerateDocument {
            get {
                return ResourceManager.GetString("btnGenerateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string btnInvoices {
            get {
                return ResourceManager.GetString("btnInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegląd faktur.
        /// </summary>
        public static string btnInvoicesView {
            get {
                return ResourceManager.GetString("btnInvoicesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedawcy.
        /// </summary>
        public static string btnVendors {
            get {
                return ResourceManager.GetString("btnVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak klientów w bazie.
        /// </summary>
        public static string customersError {
            get {
                return ResourceManager.GetString("customersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        public static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowano dokumenty.
        /// </summary>
        public static string documentsGenerated {
            get {
                return ResourceManager.GetString("documentsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja:.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość:.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorca:.
        /// </summary>
        public static string lblConsumer {
            get {
                return ResourceManager.GetString("lblConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient:.
        /// </summary>
        public static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystawienia:.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        public static string lblItem {
            get {
                return ResourceManager.GetString("lblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer rachunku:.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do plików: .
        /// </summary>
        public static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data płatności:.
        /// </summary>
        public static string lblPaymentDate {
            get {
                return ResourceManager.GetString("lblPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda płatności:.
        /// </summary>
        public static string lblPaymentMethod {
            get {
                return ResourceManager.GetString("lblPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce wystawienia:.
        /// </summary>
        public static string lblPlace {
            get {
                return ResourceManager.GetString("lblPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena za jednostkę:.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka miary:.
        /// </summary>
        public static string lblUnit {
            get {
                return ResourceManager.GetString("lblUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedawca:.
        /// </summary>
        public static string lblVendor {
            get {
                return ResourceManager.GetString("lblVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr konta:.
        /// </summary>
        public static string lblVendorBankAccount {
            get {
                return ResourceManager.GetString("lblVendorBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa banku:.
        /// </summary>
        public static string lblVendorBankName {
            get {
                return ResourceManager.GetString("lblVendorBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy:.
        /// </summary>
        public static string lblVendorCompany {
            get {
                return ResourceManager.GetString("lblVendorCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko:.
        /// </summary>
        public static string lblVendorLastName {
            get {
                return ResourceManager.GetString("lblVendorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię:.
        /// </summary>
        public static string lblVendorName {
            get {
                return ResourceManager.GetString("lblVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP:.
        /// </summary>
        public static string lblVendorNip {
            get {
                return ResourceManager.GetString("lblVendorNip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy:.
        /// </summary>
        public static string lblVendorPostCode {
            get {
                return ResourceManager.GetString("lblVendorPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string lblVendorStreet {
            get {
                return ResourceManager.GetString("lblVendorStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikat.
        /// </summary>
        public static string messageBoxStatement {
            get {
                return ResourceManager.GetString("messageBoxStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis udany.
        /// </summary>
        public static string saveSuccessful {
            get {
                return ResourceManager.GetString("saveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj odbiorcę.
        /// </summary>
        public static string ucAddConsumerView {
            get {
                return ResourceManager.GetString("ucAddConsumerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj klienta.
        /// </summary>
        public static string ucAddCustomerView {
            get {
                return ResourceManager.GetString("ucAddCustomerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista artykułów.
        /// </summary>
        public static string ucAddedItemsView {
            get {
                return ResourceManager.GetString("ucAddedItemsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sprzedawcę.
        /// </summary>
        public static string ucAddVendorView {
            get {
                return ResourceManager.GetString("ucAddVendorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreator artykułu.
        /// </summary>
        public static string ucCreateInvoiceItemView {
            get {
                return ResourceManager.GetString("ucCreateInvoiceItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreator.
        /// </summary>
        public static string ucCreator {
            get {
                return ResourceManager.GetString("ucCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artykuły.
        /// </summary>
        public static string ucItems {
            get {
                return ResourceManager.GetString("ucItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane główne.
        /// </summary>
        public static string ucMainData {
            get {
                return ResourceManager.GetString("ucMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string ucSettingsView {
            get {
                return ResourceManager.GetString("ucSettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegląd odbiorców.
        /// </summary>
        public static string ucShowConsumersView {
            get {
                return ResourceManager.GetString("ucShowConsumersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegląd klientów.
        /// </summary>
        public static string ucShowCustomersView {
            get {
                return ResourceManager.GetString("ucShowCustomersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegląd faktur.
        /// </summary>
        public static string ucShowInvoicesView {
            get {
                return ResourceManager.GetString("ucShowInvoicesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegląd sprzedawców.
        /// </summary>
        public static string ucShowVendorsView {
            get {
                return ResourceManager.GetString("ucShowVendorsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak sprzedawców w bazie.
        /// </summary>
        public static string vendorsError {
            get {
                return ResourceManager.GetString("vendorsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana ścieżka jest nieprawidłowa.
        /// </summary>
        public static string wrongPath {
            get {
                return ResourceManager.GetString("wrongPath", resourceCulture);
            }
        }
    }
}
