//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicesService {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvoicesService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szt..
        /// </summary>
        internal static string art {
            get {
                return ResourceManager.GetString("art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gotówka.
        /// </summary>
        internal static string cashMethod {
            get {
                return ResourceManager.GetString("cashMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kopia.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podpis osoby upoważnionej do odbioru rachunku.
        /// </summary>
        internal static string customerSign {
            get {
                return ResourceManager.GetString("customerSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string kilogram {
            get {
                return ResourceManager.GetString("kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP powinien mieć 10 cyfr.
        /// </summary>
        internal static string NIPValidate {
            get {
                return ResourceManager.GetString("NIPValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oryginał.
        /// </summary>
        internal static string orginal {
            get {
                return ResourceManager.GetString("orginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mb.
        /// </summary>
        internal static string runningMeter {
            get {
                return ResourceManager.GetString("runningMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2.
        /// </summary>
        internal static string squareMeter {
            get {
                return ResourceManager.GetString("squareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przelew.
        /// </summary>
        internal static string transferMethod {
            get {
                return ResourceManager.GetString("transferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podpis osoby upoważnionej do wystawienia rachunku.
        /// </summary>
        internal static string vendorSign {
            get {
                return ResourceManager.GetString("vendorSign", resourceCulture);
            }
        }
    }
}
